<?php

define('GUARDAR_MENU_SESSION',true);
define('GUARDAR_ACCIONES_SESSION',true);

define('TEXTO_REGISTRO_ACTIVO','si');
define('TEXTO_REGISTRO_INACTIVO','no');

define('REGISTRO_RELACIONADO', '23000');